### ISSUE TITLE
pidgin crashes when disabling logging

### ISSUE THREAD

**Issue by silberzwiebel** [sardemff7/purple-events#5]
Procedure to reproduce, tested with pidgin 2.10.9,  purple-events 0.2 on Sabayon with XMPP:
1) Add a MUC-chat.
2) Enter the chat.
3) Disable logging.
4) Quit Pidgin.
5) Pidgin crashes at startup.  (Sometimes it already crashes at 3) or 4))

Crash does not appear when plugin purple-events is disabled. Thats the reason I file the bug here and not over at pidgin. All other plugins were disabled, backtrace is here: 

```
#0  0x00007ffff47a6945 in malloc_consolidate () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007ffff47a7be4 in _int_malloc () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007ffff47aa8c4 in calloc () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007ffff5044909 in g_malloc0 () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#4  0x00007ffff502d980 in ?? () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#5  0x00007ffff502dfca in ?? () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#6  0x00007ffff5d5af12 in purple_dbus_unregister_pointer (node=0xc9d560) at dbus-server.c:119
        id = 0x1a13
#7  0x00007ffff5d3ddfa in purple_status_destroy (status=0xc9d560) at status.c:602
No locals.
#8  0x00007ffff503b3fd in g_list_foreach () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#9  0x00007ffff5d3f6d2 in purple_presence_destroy (presence=0xc9c3d0) at status.c:1179
        __PRETTY_FUNCTION__ = "purple_presence_destroy"
#10 0x00007ffff5cf3376 in purple_buddy_destroy (buddy=0xc9c340) at blist.c:1412
        prpl = <optimized out>
        prpl_info = <optimized out>
#11 0x00007ffff5cf4bf9 in purple_blist_node_destroy (node=0xc9c210) at blist.c:2862
        ui_ops = 0x6f09e0 <blist_ui_ops>
        child = <optimized out>
        next_child = 0x0
#12 0x00007ffff5cf4bf9 in purple_blist_node_destroy (node=0xb52b80) at blist.c:2862
        ui_ops = 0x6f09e0 <blist_ui_ops>
        child = <optimized out>
        next_child = 0xc9dab0
#13 0x00007ffff5cf8d09 in purple_blist_uninit () at blist.c:3252
        node = 0x26808f0
        next_node = 0xcdb510
#14 0x00007ffff5d084da in purple_core_quit () at core.c:227
        ops = <optimized out>
        core = 0x7e83e0
        __PRETTY_FUNCTION__ = "purple_core_quit"
#15 0x00007ffff5532f60 in g_closure_invoke () from /usr/lib64/libgobject-2.0.so.0
No symbol table info available.
#16 0x00007ffff5545070 in ?? () from /usr/lib64/libgobject-2.0.so.0
No symbol table info available.
#17 0x00007ffff554ce66 in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
No symbol table info available.
#18 0x00007ffff554d072 in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
No symbol table info available.
#19 0x00007ffff6e8ce8c in gtk_widget_activate () from /usr/lib64/libgtk-x11-2.0.so.0
No symbol table info available.
#20 0x00007ffff6d8830d in gtk_menu_shell_activate_item () from /usr/lib64/libgtk-x11-2.0.so.0
No symbol table info available.
#21 0x00007ffff6d886ac in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
No symbol table info available.
#22 0x00007ffff6d756e9 in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
No symbol table info available.
#23 0x00007ffff5532f60 in g_closure_invoke () from /usr/lib64/libgobject-2.0.so.0
No symbol table info available.
#24 0x00007ffff5544d5b in ?? () from /usr/lib64/libgobject-2.0.so.0
No symbol table info available.
#25 0x00007ffff554ca8f in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
No symbol table info available.
#26 0x00007ffff554d072 in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
No symbol table info available.
#27 0x00007ffff6e8dc5e in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
No symbol table info available.
#28 0x00007ffff6d73a54 in gtk_propagate_event () from /usr/lib64/libgtk-x11-2.0.so.0
No symbol table info available.
#29 0x00007ffff6d73dbb in gtk_main_do_event () from /usr/lib64/libgtk-x11-2.0.so.0
No symbol table info available.
#30 0x00007ffff69e359c in ?? () from /usr/lib64/libgdk-x11-2.0.so.0
No symbol table info available.
#31 0x00007ffff503eb55 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#32 0x00007ffff503ee98 in ?? () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#33 0x00007ffff503f2fa in g_main_loop_run () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#34 0x00007ffff6d72db7 in gtk_main () from /usr/lib64/libgtk-x11-2.0.so.0
No symbol table info available.
#35 0x0000000000434fd1 in main (argc=1, argv=0x7fffffffd588) at gtkmain.c:933
        opt_force_online = 0
        opt_help = <optimized out>
        opt_login = 0
        opt_nologin = 0
        opt_version = <optimized out>
        opt_si = 0
        opt_config_dir_arg = <optimized out>
        opt_login_arg = <optimized out>
        opt_session_arg = <optimized out>
        search_path = <optimized out>
        accounts = <optimized out>
        sig_indx = 1
        sigset = {__val = {82950, 0 <repeats 15 times>}}
        errmsg = "\020\000\000\000\000\000\000\000\362\373z\364\377\177\000\000\000\000\000\000\000\000\000\000\240ZQ\356\377\177\000\000\240\304\377\377\377\177\000\000\237u\244\360\377\177\000\000/usr/bin/pidgin", '\000' <repeats 633 times>...
        signal_channel = <optimized out>
        signal_status = <optimized out>
        signal_channel_watcher = 1
        segfault_message_tmp = <optimized out>
        error = 0x0
        opt = <optimized out>
        gui_check = <optimized out>
        debug_enabled = <optimized out>
        migration_failed = <optimized out>
        active_accounts = <optimized out>
        st = {st_dev = 4222451713, st_ino = 140737488340128, st_nlink = 140737488340128, st_mode = 4294952096, st_uid = 32767, st_gid = 4294952096, __pad0 = 32767, st_rdev = 140737488340143, st_size = 140737488344223, 
          st_blksize = 140737488340128, st_blocks = 140737488344223, st_atim = {tv_sec = 0, tv_nsec = 0}, st_mtim = {tv_sec = 0, tv_nsec = 0}, st_ctim = {tv_sec = 0, tv_nsec = 16}, __unused = {140737295088626, 140737298366464, 0}}
        long_options = {{name = 0x4d2d7c "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x4bd02e "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x4ce163 "force-online", has_arg = 0, flag = 0x0, val = 102}, {
            name = 0x4c06df "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x4ce02a "login", has_arg = 2, flag = 0x0, val = 108}, {name = 0x4ce170 "multiple", has_arg = 0, flag = 0x0, val = 109}, {name = 0x4ce179 "nologin", 
            has_arg = 0, flag = 0x0, val = 110}, {name = 0x4d2d72 "session", has_arg = 1, flag = 0x0, val = 115}, {name = 0x4c43db "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x4d2d85 "display", has_arg = 1, flag = 0x0, 
            val = 68}, {name = 0x4cf666 "sync", has_arg = 0, flag = 0x0, val = 83}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
```

**Comment by sardemff7** [comment]
Is is still crashing?

**Comment by silberzwiebel** [comment]
Sorry for my late reply.
Indeed, yes, pidgin still crashes. I'm not using Pidgin since some time anymore, but followed the steps I wrote at the beginning of this issue and Pidgin crashed. I'm now at Fedora 23, with Pidgin 2.10.11 and your plugin version 0.99.1.
Pidgin does not crash with purple-events disabled.

This is the backtrace I get:
```
#0  0x00005555555bb795 in pidgin_conv_has_focus ()
#1  0x00007fffd7e001d6 in purple_events_callback_conversation_updated (conv=0x55555692ee70, type=<optimized out>, context=<optimized out>) at src/plugin/callbacks.c:196
#2  0x00007ffff4e0df40 in purple_signal_emit_vargs () at /lib64/libpurple.so.0
#3  0x00007ffff4e0e09e in purple_signal_emit () at /lib64/libpurple.so.0
#4  0x00005555555c0443 in private_gtkconv_new ()
#5  0x00005555555c04cb in pidgin_conv_new ()
#6  0x00007ffff4dda795 in purple_conversation_new () at /lib64/libpurple.so.0
#7  0x00007ffff4e0cfb6 in serv_got_joined_chat () at /lib64/libpurple.so.0
#8  0x00007fffdb5e8ad1 in jabber_presence_parse () at /usr/lib64/purple-2/libjabber.so.0
#9  0x00007fffdb5d9b2b in jabber_process_packet () at /usr/lib64/purple-2/libjabber.so.0
#10 0x00007fffdb5e6644 in jabber_parser_element_end_libxml () at /usr/lib64/purple-2/libjabber.so.0
#11 0x00007ffff41dae13 in xmlParseEndTag2 () at /lib64/libxml2.so.2
#12 0x00007ffff41e099f in xmlParseTryOrFinish () at /lib64/libxml2.so.2
#13 0x00007ffff41e24bb in xmlParseChunk () at /lib64/libxml2.so.2
#14 0x00007fffdb5e6afd in jabber_parser_process () at /usr/lib64/purple-2/libjabber.so.0
#15 0x00007fffdb5d5d6b in jabber_recv_cb_ssl () at /usr/lib64/purple-2/libjabber.so.0
#16 0x00005555555c969e in pidgin_io_invoke ()
#17 0x00007ffff3025e3a in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#18 0x00007ffff30261d0 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#19 0x00007ffff30264f2 in g_main_loop_run () at /lib64/libglib-2.0.so.0
#20 0x00007ffff6b12f37 in gtk_main () at /lib64/libgtk-x11-2.0.so.0
#21 0x000055555558fdf7 in main ()
```

I hope this is informative enough, otherwise I might be able to build debug versions. But maybe I would need help with this.
